export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_NODES_NUMBER = 'CHANGE_NODES_NUMBER';
export const CHANGE_LEVELS_NUMBER = 'CHANGE_LEVELS_NUMBER';

export const UPDATE_NODES = 'UPDATE_NODES';
