export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_NODES_NUMBER = 'CHANGE_NODES_NUMBER';
export const CHANGE_LEVELS_NUMBER = 'CHANGE_LEVELS_NUMBER';
export const UPDATE_NODE_LIST = 'UPDATE_NODE_LIST';
export const BUILD_NODE_LIST = 'BUILD_NODE_LIST';
