export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_PENDING = `${FETCH_USERS}_PENDING`;
export const FETCH_USERS_RECEIVE = `${FETCH_USERS}_FULFILLED`;
export const FETCH_USERS_ERROR = `${FETCH_USERS}_REJECTED`;
